config/routes.rb
GameOfDom::Application.routes.draw do
  
  root :to => 'home#index'

  get '/ajax-messages/welcome' => 'messages#welcome'
  get '/ajax-messages/fight' => 'messages#fight'
  get '/ajax-messages/finish' => 'messages#finish'
  
  resources :battles

  resources :divs

  resources :pages

end

app/models/battle.rb
# == Schema Information
#
# Table name: battles
#
#  id         :integer          not null, primary key
#  score      :integer
#  winner_id  :integer
#  loser_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Battle < ActiveRecord::Base
  attr_accessible :score, :winner_id, :loser_id

  # relationships
  belongs_to :winner, :class_name => :Div
  belongs_to :loser, :class_name => :Div

end

app/models/div.rb
# == Schema Information
#
# Table name: divs
#
#  id         :integer          not null, primary key
#  content    :text
#  element    :string(255)
#  page_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Div < ActiveRecord::Base
  attr_accessible :content, :page_id
  # validation - needs to have a url and title
  validates :content, :presence => true
  validates :page_id, :presence => true
  # relationships
  belongs_to :page
  has_many(:battles, :foreign_key => :winner_id) 
  has_many(:conquests, :through => :battles, :source => :loser)
  
  #has_many(:conquests, :class_name => :Battle, :foreign_key => :loser_id)

  #self-join relationships
  # scenes
  # has_many(:battles, :foreign_key => :winner_id)
  # has_many(:conquests, :through => :battles, :source => :loser)

  # tracks
  # belongs_to :origin, :class_name => :Scene
  # belongs_to :destination, :class_name => :Scene

  #self-join relationships
  # scenes
  # has_many(:tracks, :foreign_key => :origin_id, :dependent => :destroy)
  # has_many(:destinations, :through => :tracks, :source => :destination)

  # tracks
  # belongs_to :origin, :class_name => :Scene
  # belongs_to :destination, :class_name => :Scene

end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  title      :string(255)
#  favicon    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Page < ActiveRecord::Base
  attr_accessible :url, :title, :favicon
  # validation - needs to have a url and title
  validates :url, :presence => true
  validates :title, :presence => true
  # relationships
  has_many :divs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController

  after_action :set_access_control_headers, only: [:create]

  protect_from_forgery :secret => 'iLikeH0tD0gs',  
                       :except => :create

  after_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = "*"
    headers['Access-Control-Request-Method'] = %w{GET POST OPTIONS}.join(",")
  end

  def index
    @battles = Battle.all
  end

  def show
  end

  # GET /battles/1/edit
  def edit
  end

  def create
    
    # create new battle object
    battle = Battle.new
    battle.score = params[:score]
    # create new winner div
    battle.winner = Div.new 
    battle.winner.element = params[:winner][:element]
    # create new loser div
    battle.loser = Div.new
    battle.loser.element = params[:loser][:element]
    battle.winner.content = 'I beat a ' + battle.loser.element
    battle.loser.content = 'I lost to a ' + battle.winner.element
    # create new page, if page not exist
    page_match = Page.where("url" => params[:page][:url])
    if page_match.present?
      battle.winner.page = page_match.first
    else
      battle.winner.page = Page.new
      battle.winner.page.url = params[:page][:url]
      battle.winner.page.title = params[:page][:title]
      
      battle.winner.page.save
    
    end
    # save winner/loser with page
    battle.winner.page_id = battle.winner.page.id    
    battle.loser.page_id = battle.winner.page.id
    
    battle.winner.save
    battle.loser.save
    
    # save the battle
    battle.winner_id = battle.winner.id
    battle.loser_id = battle.loser.id
    
    battle.save

    if battle.save
      render :json => true
    else
      render :json => false
    end

  end

  def destroy
    @battle = Battle.find(params[:id])
    @battle.destroy
  end

end

app/controllers/divs_controller.rb
class DivsController < ApplicationController

  def index
    @divs = Div.all
  end

  def destroy
    @div = Div.find(params[:id])
    @div.destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @battles = Battle.all.order("score DESC")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  after_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = "*"
    headers['Access-Control-Request-Method'] = %w{GET POST OPTIONS}.join(",")
  end

  def welcome
    render :json => '{
                      "class":"welcome",
                      "html":"<div><h1>Click two parts of the page to see who will win!<\/h1><p><a href=\'http:\/\/divandconquer.herokuapp.com\/\'>&lt;div&gt;&amp;conquer leaderboard<\/a><\/p><p><a href=\'http:\/\/github.com\/citizengit\'>a GA WDI student project by Kriss Heimanis<\/a><\/p><\/div>"
                    }'
  end

  def fight
    render :json => '{
                      "class":"fight",
                      "html":"<div><h1 id=\'fight\'>Which dom object on screen will reign supreme?<\/h1><table><tr><td><h1 id=\'nameOne\'><\/h1><\/td><td><h4>vs<\/h4><\/td><td><h1 id=\'nameTwo\'><\/h1><\/td><\/tr><tr><td><h1 id=\'scoreOne\'>0<\/h1><\/td><td><h6>score<\/h6><\/td><td><h1 id=\'scoreTwo\'>0<\/h1><\/td><\/tr><tr><td><h3 id=\'healthOne\'>0<\/h3><\/td><td><h6>current health<\/h6><\/td><td><h3 id=\'healthTwo\'>0<\/h3><\/td><\/tr><tr><td><h4 id=\'powerOne\'>0<\/h4><\/td><td><h6>current power<\/h6><\/td><td><h4 id=\'powerTwo\'>0<\/h4><\/td><\/tr><tr><td><h4 id=\'hitOne\'>0<\/h4><\/td><td><h6>this hit<\/h6><\/td><td><h4 id=\'hitTwo\'>0<\/h4><\/td><\/tr><\/table><\/div>"
                    }'
  end

  def finish
    render :json => '{
                      "class":"finish",
                      "html":"<div><h1 id=\'playAgain\'>PLAY AGAIN<\/h1><p><a href=\'http:\/\/divandconquer.herokuapp.com\/\'>&lt;div&gt;&amp;conquer leaderboard<\/a><\/p><p><a href=\'http:\/\/github.com\/citizengit\'>a GA WDI student project by Kriss Heimanis<\/a><\/p><\/div>"
                    }'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/divs_helper.rb
module DivsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/battles/_form.html.erb
<%= form_for(@battle) do |f| %>
  <% if @battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% @battle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/battles/edit.html.erb
<h1>Editing battle</h1>

<%= render 'form' %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>

app/views/battles/index.html.erb
<div id="GDMessageContainer" class="GoDText">

<div>
  <h1>Click two parts of the page to see who will win!</h1>
  <p><a href="http://divandconquer.herokuapp.com/">&lt;div&gt;&amp;conquer leaderboard</a></p>
  <p><a href="http://github.com/citizengit">a GA WDI student project by Kriss Heimanis</a></p>
</div>

<div>
  <h1 id='fight'>Which dom object on screen will reign supreme?</h1>
  <table>
    <tr><td><h1 id='nameOne'></h1></td><td><h4>vs</h4></td><td><h1 id='nameTwo'></h1></td></tr>
    <tr><td><h1 id='scoreOne'>0</h1></td><td><h6>score</h6></td><td><h1 id='scoreTwo'>0</h1></td></tr>
    <tr><td><h3 id='healthOne'>0</h3></td><td><h6>current health</h6></td><td><h3 id='healthTwo'>0</h3></td></tr>
    <tr><td><h4 id='powerOne'>0</h4></td><td><h6>current power</h6></td><td><h4 id='powerTwo'>0</h4></td></tr>
    <tr><td><h4 id='hitOne'>0</h4></td><td><h6>this hit</h6></td><td><h4 id='hitTwo'>0</h4></td></tr>
  </table>
</div>

<div>
  <h1 id="playAgain">PLAY AGAIN</h1>
  <p><a href="http://divandconquer.herokuapp.com/">&lt;div&gt;&amp;conquer leaderboard</a></p>
  <p><a href="http://github.com/citizengit">a GA WDI student project by Kriss Heimanis</a></p>
</div>

</div>
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td><%= link_to 'Show', battle %></td>
        <td><%= link_to 'Edit', edit_battle_path(battle) %></td>
        <td><%= link_to 'Destroy', battle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battle', new_battle_path %>

app/views/battles/new.html.erb
<h1>New battle</h1>

<%= render 'form' %>

<%= link_to 'Back', battles_path %>

app/views/battles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_battle_path(@battle) %> |
<%= link_to 'Back', battles_path %>

app/views/divs/_form.html.erb
<%= form_for(@div) do |f| %>
  <% if @div.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@div.errors.count, "error") %> prohibited this div from being saved:</h2>

      <ul>
      <% @div.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/divs/edit.html.erb
<h1>Editing div</h1>

<%= render 'form' %>

<%= link_to 'Show', @div %> |
<%= link_to 'Back', divs_path %>

app/views/divs/index.html.erb
<h1>Listing divs</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @divs.each do |div| %>
      <tr>
        <td><%= link_to 'Show', div %></td>
        <td><%= link_to 'Edit', edit_div_path(div) %></td>
        <td><%= link_to 'Destroy', div, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Div', new_div_path %>

app/views/divs/new.html.erb
<h1>New div</h1>

<%= render 'form' %>

<%= link_to 'Back', divs_path %>

app/views/divs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_div_path(@div) %> |
<%= link_to 'Back', divs_path %>

app/views/home/index.html.erb
<img src="http://divandconquer.herokuapp.com/assets/div-logo-02.png" alt="<DIV>&CONQUER">
<h1>The Web is a Tough Place</h1>
<h3>Select the Right &lt;div&gt; and Conquer</h3>
<p>The game is simple, start the game pick any two elements on any page and watch them fight to the death. Make any webpage your plaything!</p>
<h1>Are There Rules?</h1>
<p>Loose rules are - whatever you click on the page will battle with it's last child element first, and make it's way up through it's stack until it is dead. Inside this, certain elements are stronger than others, the hierarchy runs like this: </p>
<ul>
  <li>&lt;p&gt; &lt;br&gt; &lt;span&gt; &lt;td&gt; = 10</li>
  <li>&lt;ul&gt; &lt;ol&gt; &lt;li&gt; &lt;tr&gt; &lt;table&gt; &lt;th&gt; = 25</li>
  <li>&lt;tbody&gt; &lt;h1&gt; &lt;h2&gt; &lt;h3&gt; &lt;h4&gt; &lt;h5&gt; &lt;h6&gt; = 30</li>
  <li>&lt;div&gt; &lt;section&gt; &lt;article&gt; = 35</li>
  <li>&lt;footer&gt; &lt;header&gt; = 40</li>
  <li>&lt;img&gt; &lt;video&gt; = 50</li>
  <li>&lt;a&gt; = 60</li>
</ul> 
<p>Because we all know that the &lt;a&gt; tag is the king of the web!</p>
<h1>Gosh That Sounds Fun - How Can I Play</h1>
<h3>Drag this link to your bookmarks bar --&gt; <a href="javascript:var%20i,s,ss=['//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js','http://divandconquer.herokuapp.com/assets/game-dom.js'];for(i=0;i!=ss.length;i++){s=document.createElement('script');s.src=ss[i];document.body.appendChild(s);}void(0);">&lt;div&gt;&amp;CONQUER</a> &lt;<-- Click it on ANY site that you think needs some life!</h3>
<h1>But This Breaks Websites - I Might Get in Trouble?</h1>
<p>Fear not, this doesn't have any permanent effect on the website on which you play it, all the effects are just temporarily created by (huge and confusing strings) of JavaScript code that goes away as soon as you leave the page. So go nuts. If anything you're helping the other websites, as a link to all the sites that get played will appear on this site, and that's called SEO or SEF or SEM or link-farming or social-networking or something, and everybody loves that shit.</p>
<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Winning Element</th>
      <th>Losing Element</th>
      <th>Content</th>
      <th>URL</th>
      <th>Page</th>
    </tr>

  </thead>

  <tbody>
    <% @battles.each do |battle| %>
      <tr class="<%= cycle('even', 'odd') -%>">
        <td><%= battle.score %></td>
        <td><%= battle.winner.element %></td>
        <td>
          <% battle.winner.conquests.each do |conquest| %>
            <%= conquest.element %>
          <% end %>
        </td>
        <td><%= battle.winner.content %></td>
        <td><a href="<%= battle.winner.page.url %>" target="_blank"><%= battle.winner.page.url %></a></td>
        <td><%= battle.winner.page.title %></td>
      </tr>

    <% end %>
  </tbody>

</table>
<h1>Why &lt;div&gt;&amp;conquer?</h1>
<p>Div and conquer is a silly game made by a student trying to push what he could do with JQuery. The original idea was to make a webpage into a gameboard, inspired by the game of thrones opening animations, where flat landscapes build into 3D fortresses. I wanted to do the same thing with any webpage you might decide needs some life, and then be able to battle between these elements. A week is not a long time to do this, but that was all we had, so somewhere along the way game-of-doms changed course and became more of a cage match for page elements. Oh well.</p>



<a href="https://github.com/citizengit"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/c6625ac1f3ee0a12250227cf83ce904423abf351/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png"></a>

<!-- AddThis Smart Layers BEGIN -->
<!-- Go to http://www.addthis.com/get/smart-layers to customize -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4eb87d6f714bfbe9"></script>
<script type="text/javascript">
  addthis.layers({
    'theme' : 'light',
    'share' : {
      'position' : 'left',
      'numPreferredServices' : 5
    }, 
    'follow' : {
      'services' : [
        {'service': 'twitter', 'id': 'modeltwitizen'}
      ]
    },  
    'whatsnext' : {}  
  });
</script>


<!-- AddThis Smart Layers END -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>&lt;div&gt;&amp;CONQUER - it's eleMENTAL!</title>
  <link rel="shortcut icon" href="/favicon.ico" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49479736-4', 'divandconquer.herokuapp.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>